# Generated by Django 2.0.1 on 2018-12-10 19:40

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageTitle', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='网站轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100, verbose_name='商品名')),
                ('ProductDesc', models.CharField(max_length=500, verbose_name='商品描述')),
                ('ProductInfo', DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情介绍')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('Category', models.CharField(default=' ', max_length=50, verbose_name='商品种类')),
                ('DealNum', models.IntegerField(default=0, verbose_name='交易成功数')),
                ('LikeNum', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('you_must_know', models.CharField(default='无', max_length=300, verbose_name='店家提醒')),
                ('ProductImage', models.ImageField(upload_to='commodity/%Y/%m', verbose_name='商品封面图')),
                ('ClickNum', models.IntegerField(default=0, verbose_name='点击量')),
                ('tag', models.CharField(default='', max_length=15, verbose_name='商品标签')),
                ('ProductDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('Apply', models.CharField(max_length=10, verbose_name='适用人群')),
                ('RemainNum', models.IntegerField(default=0, verbose_name='剩余数量')),
                ('IfBanner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('product_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='所属品牌')),
                ('product_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name_plural': '商品',
                'verbose_name': '商品',
            },
        ),
    ]
