# Generated by Django 2.0.1 on 2018-12-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20181218_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductDesc',
        ),
    ]
