# Generated by Django 2.0.1 on 2018-12-10 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=50, verbose_name='品牌名称')),
                ('BrandDesc', models.CharField(default='', max_length=300, verbose_name='品牌描述')),
                ('ClickNum', models.IntegerField(default=0, verbose_name='点击量')),
                ('LikeNum', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('BrandImage', models.ImageField(upload_to='brand/%Y/%m', verbose_name='品牌logo')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('feature', models.CharField(max_length=50, verbose_name='品牌特点')),
            ],
            options={
                'verbose_name_plural': '品牌',
                'verbose_name': '品牌',
            },
        ),
        migrations.CreateModel(
            name='BrandToShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='商家拥有的品牌名')),
            ],
            options={
                'verbose_name_plural': '品牌店铺关系',
                'verbose_name': '品牌店铺关系',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=20, verbose_name='城市')),
            ],
            options={
                'verbose_name_plural': '城市',
                'verbose_name': '城市',
            },
        ),
        migrations.CreateModel(
            name='KindToShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '商品种类店铺关系',
                'verbose_name': '商品种类店铺关系',
            },
        ),
        migrations.CreateModel(
            name='SaleKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KindName', models.CharField(max_length=10, verbose_name='商品种类')),
            ],
            options={
                'verbose_name_plural': '商品种类',
                'verbose_name': '商品种类',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=50, verbose_name='商家名称')),
                ('ShopDesc', models.TextField(verbose_name='商家描述')),
                ('ShopKind', models.CharField(choices=[('Personal', '个人店铺'), ('BrandShop', '品牌直营'), ('official', '官方自营')], max_length=20, verbose_name='商家类别')),
                ('ShopTag', models.CharField(max_length=20, verbose_name='商家标签')),
                ('ClickNum', models.IntegerField(default=0, verbose_name='点击量')),
                ('LikeNum', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('ShopImage', models.ImageField(upload_to='shop/%Y/%m', verbose_name='店铺封面图')),
                ('address', models.CharField(default='', max_length=100, verbose_name='商家地址')),
                ('ProductNum', models.IntegerField(default=0, verbose_name='卖的商品数')),
                ('ShopDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='店铺添加时间')),
                ('DealNum', models.IntegerField(default=0, verbose_name='交易成功数')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.City', verbose_name='店家所在地')),
            ],
            options={
                'verbose_name_plural': '店铺',
                'verbose_name': '店铺',
            },
        ),
        migrations.AddField(
            model_name='kindtoshop',
            name='KindName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SaleKind', verbose_name='商家拥有的产品种类'),
        ),
        migrations.AddField(
            model_name='kindtoshop',
            name='ShopName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='产品种类属于的商家名'),
        ),
        migrations.AddField(
            model_name='brandtoshop',
            name='ShopName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='品牌属于的商家名'),
        ),
        migrations.AddField(
            model_name='brand',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SaleKind', verbose_name='售卖种类'),
        ),
    ]
