# Generated by Django 2.0.1 on 2018-12-19 04:06

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ShopDesc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='店铺详情介绍'),
        ),
    ]
