# Generated by Django 2.0.1 on 2018-12-10 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户姓名')),
                ('mobileNumber', models.CharField(max_length=11, verbose_name='联系电话')),
                ('ProductName', models.CharField(max_length=50, verbose_name='产品名')),
                ('AskTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name_plural': '用户需求',
                'verbose_name': '用户需求',
            },
        ),
        migrations.CreateModel(
            name='UserBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '用户购买',
                'verbose_name': '用户购买',
            },
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250, verbose_name='用户评论')),
                ('CommentTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name_plural': '商品评论',
                'verbose_name': '商品评论',
            },
        ),
        migrations.CreateModel(
            name='UserLove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoveId', models.IntegerField(default=0)),
                ('LoveType', models.IntegerField(choices=[(1, '商品'), (2, '店铺'), (3, '品牌')], default=1, verbose_name='喜欢类型')),
                ('LoveTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name_plural': '用户收藏',
                'verbose_name': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='接收用户')),
                ('message', models.CharField(max_length=300, verbose_name='消息内容')),
                ('haveRead', models.BooleanField(default=False, verbose_name='是否已读')),
                ('SendTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name_plural': '用户消息',
                'verbose_name': '用户消息',
            },
        ),
    ]
