# Generated by Django 2.0.1 on 2018-12-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperate', '0002_auto_20181210_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlove',
            name='LoveId',
            field=models.IntegerField(default=0, verbose_name='收藏id'),
        ),
        migrations.AlterField(
            model_name='userlove',
            name='LoveType',
            field=models.IntegerField(choices=[(1, '商品'), (2, '店铺'), (3, '品牌')], default=1, verbose_name='收藏类型'),
        ),
    ]
