# Generated by Django 2.0.1 on 2018-12-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userOperate', '0003_auto_20181218_0248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAsk',
        ),
    ]
